[Variables]
;;; GLOBAL

; Fonts
; Anurati | Quicksand | Aquatico
ClockFont=Anurati
FontFace1=Quicksand
FontFace2=Aquatico

; Colors
; https://goo.gl/search/color+picker
MainColor=255,255,255
AccentColor=250,126,0

;;; CLOCK

; https://docs.rainmeter.net/manual/measures/time/#Format
MeasureTimeFormat=%H:%M

;;; PLAYER

; WebNowPlaying | NowPlaying
PlayerPlugin=WebNowPlaying
; Only works with PlayerPlugin=NowPlaying
; https://docs.rainmeter.net/manual/measures/nowplaying/
PlayerName=CAD

;;; WEATHER

; SiteIcons | RealisticIcons
IconStyle=SiteIcons

;;; INTERNAL

ScrollMouseIncrement=0.1