[Variables]
;;; GLOBAL

; Fonts
; Acceptable values
; Anurati | Quicksand | Aquatico
ClockFont=Anurati
FontFace1=Quicksand
FontFace2=Aquatico

; Colors 
; In RGB https://goo.gl/search/color+picker
MainColor=255,255,255
AccentColor=250,126,0

;;; CLOCK

; Acceptable values 
; https://docs.rainmeter.net/manual/measures/time/#Format
MeasureTimeFormat=%H:%M

;;; PLAYER

; Acceptable values
; WebNowPlaying | NowPlaying
PlayerPlugin=WebNowPlaying

; PlayerName Only works with PlayerPlugin=NowPlaying
; https://docs.rainmeter.net/manual/measures/nowplaying/#playerlist
PlayerName=CAD

;;; WEATHER

; Acceptable values
; SiteIcons | RealisticIcons
IconStyle=SiteIcons

;;; INTERNAL

; Acceptable values
; https://en.wikipedia.org/wiki/Real_number
ScrollMouseIncrement=0.1
