[InfoBase]
DynamicVariables=1
SolidColor=
FontSize=(14 * #Scale#)
FontColor=#CoverMainColor#,(#MouseOver# = 0 ? #CoverInfo# : #CoverInfoOnHover#)
StringAlign=CenterCenter
StringCase=#StringCase#
FontFace=#FontFace#
AntiAlias=1
Y=(5 * #Scale#)R

[MeterInfo]
Meter=String
MeasureName=MeasureArtist
MeterStyle=InfoBase
X=(#CoverWidth# / 2 * #Scale#)
W=(#CoverWidth# * #Scale# * 0.9)
Y=(#CoverHeight# * #Scale# / 2)
ClipString=2
ClipStringH=(#CoverHeight# / 2)
InlineSetting=#CoverInfoInlinePattern#
InlinePattern=#CoverrInfoInlinePattern#
